name: Flutter Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      # Extract version name from pubspec.yaml
      - name: Get version name
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d '+' -f 1 | cut -d ' ' -f2)
          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV

      # Build APK
      - name: Build APK
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          flutter build apk \
            --release \
            --build-name=$VERSION_NAME \
            --build-number=$BUILD_NUMBER
          
          # Define and rename the final APK
          APK_NAME="jarvis_v${VERSION_NAME}_${BUILD_NUMBER}.apk"
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/$APK_NAME
          
          # Store paths and names for next steps
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
          echo "APK_PATH=build/app/outputs/flutter-apk/$APK_NAME" >> $GITHUB_ENV

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_PATH }}

      # Firebase Distribution
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase
        if: success()
        run: |
          firebase appdistribution:distribute ${{ env.APK_PATH }} \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "testers"
